/* COP32 companion — CLICKABLE PROTOTYPE, "Highland Mist" visual design (D53). Sample data only. Vanilla JS, no dependencies.
   IA unchanged (D16 v2): 5 tabs + header actions; every hash route from v1 still resolves (tree-test T1–T12). */
(() => {
const D = window.DATA, ICONS = window.ICONS || {}, $ = (s, r = document) => r.querySelector(s);
const store = { get(k, d) { try { const v = localStorage.getItem('p_' + k); return v === null ? d : JSON.parse(v); } catch { return d; } },
  set(k, v) { try { localStorage.setItem('p_' + k, JSON.stringify(v)); } catch {} },
  clear() { try { Object.keys(localStorage).filter(k => k.startsWith('p_')).forEach(k => localStorage.removeItem(k)); } catch {} } };
const S = { lang: store.get('lang', 'en'), theme: store.get('appearance', 'light'), scale: store.get('scale', 1), reduce: store.get('reduce', false), save: store.get('dataSaver', false),
  offline: typeof navigator !== 'undefined' && navigator.onLine === false, phase: store.get('phase', 'during'), saved: new Set(store.get('saved', [])), task: store.get('task', null), visited: [], firstTab: null, results: store.get('results', []), signed: store.get('signed', false) };
// ---- i18n: AM strings are MACHINE-DRAFTED & UNVERIFIED; missing ones fall back to visible English (IA rule 5)
const AM = { Home:'መነሻ', Programme:'ፕሮግራም', Map:'ካርታ', Visit:'ጉብኝት', Updates:'ዜና', Search:'ፈልግ', Settings:'ቅንብሮች', Language:'ቋንቋ', Help:'እገዛ', Today:'ዛሬ',
  'Open to public':'ለሕዝብ ክፍት', Save:'አስቀምጥ', Saved:'ተቀምጧል', 'Welcome':'እንኳን ደህና መጡ', 'Emergency & help':'ድንገተኛ አደጋ', Schedule:'መርሐ ግብር', Speakers:'ተናጋሪዎች', Menu:'ምናሌ', Back:'ተመለስ',
  'Climate finance':'የአየር ንብረት ፋይናንስ', Water:'ውሃ', Energy:'ኃይል', Youth:'ወጣቶች', Health:'ጤና', 'Up next':'ቀጣይ', Shortcuts:'አቋራጮች', 'My agenda':'የእኔ መርሐ ግብር', 'Browse programme':'ፕሮግራሙን ይመልከቱ', 'Sessions, places, people':'ስብሰባዎች፣ ቦታዎች፣ ሰዎች' };
const t = en => (S.lang === 'am' && AM[en]) ? `<span lang="am">${AM[en]}</span>` : (S.lang === 'am' ? `<span class="pending" lang="en" title="Translation pending">${en}<sup>EN</sup></span>` : en);
const tp = en => (S.lang === 'am' && AM[en]) ? AM[en] : en;  // plain text (attributes)
const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const svg = (n, cls = '') => `<svg class="i ${cls}" viewBox="0 0 24 24" aria-hidden="true" focusable="false">${ICONS[n] || ''}</svg>`;
const chev = () => svg('chevron-right', 'chev');
const fold = s => { s = (s || '').normalize('NFC'); const ones = {}, tens = {}; for (let i = 0; i < 9; i++) { ones[String.fromCharCode(0x1369 + i)] = i + 1; tens[String.fromCharCode(0x1372 + i)] = (i + 1) * 10; }
  s = s.replace(/[፩-፺]+/g, m => [...m].reduce((a, c) => a + (ones[c] || tens[c] || 0), 0));
  const M = { 0x1210: 0x1200, 0x1280: 0x1200, 0x1220: 0x1230, 0x12D0: 0x12A0, 0x1340: 0x1338 };
  s = [...s].map(c => { const p = c.codePointAt(0); for (const k in M) { if (p >= +k && p < +k + 8) return String.fromCodePoint(M[k] + p - +k); } return c; }).join('');
  return s.toLowerCase().replace(/[፠-፨]|[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g, ' ').trim(); };
const sTitle = s => S.lang === 'am' ? s.title_am : s.title_en;
const DAYS = [...new Set(D.sessions.map(s => s.day))].sort();
const dayLabel = d => { try { return new Intl.DateTimeFormat('en-GB', { weekday: 'short', day: 'numeric', timeZone: 'UTC' }).format(Date.parse(d + 'T00:00:00Z')); } catch { return d.slice(5); } };
const mins = s => { const [a, b] = s.start.split(':').map(Number), [c, d] = s.end.split(':').map(Number); return (c * 60 + d) - (a * 60 + b); };
// ---- time: sample sessions in EAT (UTC+3); show user time when different
function timeStr(s) { let out = `${dayLabel(s.day)} · ${s.start}–${s.end} EAT`;
  try { const off = -new Date().getTimezoneOffset(); if (off !== 180) { const utc = Date.parse(`${s.day}T${s.start}:00+03:00`); out += ` · ${new Intl.DateTimeFormat(S.lang === 'am' ? 'am-ET' : 'en-GB', { hour: '2-digit', minute: '2-digit' }).format(utc)} your time`; } } catch {} return out; }
// ---- illustrated, faceless avatars (no photos of real people)
const AVC = [['--c-primarySoft', '--c-primary'], ['--c-warningBg', '--c-sunset'], ['--c-successBg', '--c-success'], ['--c-infoBg', '--c-info']];
function avatar(id, big) { const PE = window.PEOPLE, pp = PE && PE.P[id] ? { ...PE.P[id], prop: PE.P[id].prop === 'hardhat' ? 'hardhat' : null } : null, n = parseInt(String(id).replace(/\D/g, ''), 10) || 0, [bg] = AVC[n % 4];
  return `<svg class="av ${big ? 'lg' : ''}" viewBox="-40 -126 80 80" aria-hidden="true"><rect x="-40" y="-126" width="80" height="80" fill="var(${bg})"/>${pp ? PE.person(pp, 0, 0, 1) : ''}</svg>`; }
// ---- shell
const app = $('#app');
function setPrefs() { const r = document.documentElement; r.style.setProperty('--scale', S.scale); r.dataset.reduce = S.reduce; r.classList.toggle('big', S.scale >= 1.5); document.body.dataset.uiLang = S.lang; r.lang = S.lang;
  if (S.theme === 'auto') r.removeAttribute('data-theme'); else r.dataset.theme = S.theme;
  const dark = S.theme === 'dark' || (S.theme === 'auto' && matchMedia('(prefers-color-scheme: dark)').matches), m = document.querySelector('meta[name=theme-color]'); if (m) m.content = dark ? '#000000' : '#F2F6F4'; }
const route = () => (location.hash.replace(/^#\/?/, '') || 'home');
const TABS = [['home', 'Home', 'house'], ['programme', 'Programme', 'calendar'], ['map', 'Map', 'map'], ['visit', 'Visit', 'luggage'], ['updates', 'Updates', 'newspaper']];
const largeTitle = (title, eyebrow = '', extra = '') => `<div class="lt"><div>${eyebrow ? `<div class="eyebrow">${eyebrow}</div>` : ''}<h1 class="title">${title}</h1></div>${extra}</div>`;
const segc = (items, cur, base) => `<nav class="segc" aria-label="Sections">${items.map(([k, l]) => `<a href="#/${base}/${k}" ${cur === k ? 'aria-current="true"' : ''}>${t(l)}</a>`).join('')}</nav>`;
const row = ({ href = '#', icon, tone = '', title, sub = '', val = '', attrs = '', noChev = false }) => `<a class="row ${icon ? '' : 'notile'}" href="${href}" ${attrs}>${icon ? `<span class="ri ${tone}">${svg(icon)}</span>` : ''}<span class="rt"><b>${title}</b>${sub ? `<small>${sub}</small>` : ''}</span>${val ? `<span class="val">${val}</span>` : ''}${noChev ? '' : chev()}</a>`;
const access = s => s.open_to_public ? `<span class="pub">${t('Open to public')}</span>` : 'Badge required';
const starBtn = s => { const sv = S.saved.has(s.id); return `<button class="star" data-save="${s.id}" aria-pressed="${sv}" aria-label="${sv ? 'Remove from' : 'Save to'} My agenda: ${esc(s.title_en)}">${svg('star')}</button>`; };
const sessRow = s => `<div class="row time"><a href="#/session/${s.id}" class="rt" style="color:inherit;text-decoration:none;flex-direction:row;gap:var(--s-4);align-items:center"><span class="tcol"><b>${s.start}</b><small>${mins(s)} min</small></span><span class="rt"><b lang="${S.lang}">${esc(sTitle(s))}</b><small>${esc(s.room)} · ${access(s)}</small></span></a>${starBtn(s)}</div>`;
const sevIcon = k => k === 'info' || k === 'success' ? 'info' : 'triangle-alert';
const notice = (kind, title, sub = '', time = '') => `<div class="notice ${kind}" role="${kind === 'critical' ? 'alert' : 'status'}">${svg(sevIcon(kind))}<div><b>${title}</b>${sub ? `<span>${sub}</span>` : ''}</div>${time ? `<time>${time}</time>` : ''}</div>`;
const emptyState = (a, b, icon = 'bookmark', cta = '') => `<div class="empty"><span class="ri">${svg(icon)}</span><b>${a}</b><p class="muted">${b}</p>${cta}</div>`;
const notFound = () => largeTitle('Not here') + emptyState('Page not found', 'This prototype does not include this screen.', 'circle-help');
const hills = `<svg class="hills" viewBox="0 0 340 110" preserveAspectRatio="none" aria-hidden="true"><path d="M0 110V62q60-30 130-10t120-6 90 10v54z" fill="#2A8285" opacity=".45"/><path d="M0 110V84q90-26 180-6t160-8v40z" fill="#0A3A3E" opacity=".9"/><path d="M286 84V68M268 66q18-11 36 0M273 71q13-7 26 0" stroke="#9BE15D" stroke-width="2.2" fill="none" stroke-linecap="round"/></svg><span class="sun" aria-hidden="true"></span>`;
// ---- illustrated covers (original SVG scenes; no photos, no logos). One scene per theme, colours fixed so they read in light and dark.
const SCENE = {
  'Water': ['#1F6F8B', '#2A9DB5', g => `<path d="M0 104q40-16 80 0t80 0 80 0 80 0v56H0z" fill="#7FD1E3" opacity=".7"/><path d="M0 124q40-14 80 0t80 0 80 0 80 0v36H0z" fill="#BDEBF3"/><circle cx="${250 - g * 9}" cy="42" r="18" fill="#FFE08A"/>`],
  'Forests': ['#1E5A3A', '#2E7D4F', g => [40, 95, 150, 205, 260].map((x, i) => `<path d="M${x + g * 3} ${150 - (i % 2) * 14}l24-${70 - (i % 3) * 10} 24 ${70 - (i % 3) * 10}z" fill="${i % 2 ? '#9BE15D' : '#5FB36A'}"/><rect x="${x + g * 3 + 21}" y="${146 - (i % 2) * 14}" width="6" height="16" fill="#3E2A1A"/>`).join('') + `<circle cx="270" cy="36" r="14" fill="#FFE08A" opacity=".85"/>`],
  'Energy': ['#D9761F', '#F2B33D', g => `<circle cx="${230 - g * 8}" cy="58" r="28" fill="#FFE08A"/>${[0, 1, 2, 3, 4, 5, 6, 7].map(i => `<path d="M${230 - g * 8} 58l${Math.cos(i * .785) * 50} ${Math.sin(i * .785) * 50}" stroke="#FFF2C4" stroke-width="4" stroke-linecap="round" opacity=".7"/>`).join('')}<path d="M20 150l40-36h70l-40 36zM110 150l40-36h70l-40 36z" fill="#1F4D6B"/><path d="M60 114l-10 9h70M150 114l-10 9h70" stroke="#7FB8D9" stroke-width="2"/>`],
  'Cities': ['#2E4057', '#4A6382', g => [10, 50, 82, 130, 168, 214, 252, 288].map((x, i) => { const h = 40 + ((i * 37 + g * 11) % 70); return `<rect x="${x}" y="${160 - h}" width="${30 + (i % 2) * 8}" height="${h}" rx="3" fill="${i % 3 ? '#9FB3C8' : '#C5D3E2'}"/>${h > 70 ? `<rect x="${x + 8}" y="${170 - h}" width="6" height="6" fill="#FFE08A"/><rect x="${x + 18}" y="${184 - h}" width="6" height="6" fill="#FFE08A"/>` : ''}`; }).join('') + `<circle cx="60" cy="34" r="12" fill="#FFE08A" opacity=".8"/>`],
  'Agriculture': ['#8A6D1F', '#C49A2C', g => `<circle cx="${70 + g * 10}" cy="44" r="18" fill="#FFF2C4"/><path d="M0 100q160-30 320 0v60H0z" fill="#9BE15D"/>${[0, 1, 2, 3, 4].map(i => `<path d="M${-20 + i * 70} 160Q${60 + i * 40} 110 ${160 + i * 10} 100" stroke="#5E8F2B" stroke-width="4" fill="none" opacity=".7"/>`).join('')}<path d="M0 132q160-20 320 0v28H0z" fill="#E8C766"/>`],
  'Youth': ['#5B3FB0', '#8E6BE0', g => `<circle cx="${70 + g * 6}" cy="60" r="30" fill="#FFD166"/><circle cx="170" cy="${96 - g * 4}" r="40" fill="#9BE15D" opacity=".85"/><circle cx="260" cy="54" r="22" fill="#FF8A65"/><circle cx="230" cy="130" r="12" fill="#FFF"/><circle cx="40" cy="130" r="8" fill="#FFF" opacity=".7"/>`],
  'Health': ['#B3463E', '#E07A6F', g => `<path d="M0 96h${90 + g * 6}l14-34 20 64 16-46 10 16h170" stroke="#FFF" stroke-width="5" fill="none" stroke-linecap="round" stroke-linejoin="round"/><path d="M250 50c-10-14-32-8-32 8 0 16 32 30 32 30s32-14 32-30c0-16-22-22-32-8z" fill="#FFD6D1"/>`],
  'Education': ['#155E63', '#2A8285', g => `<rect x="${60 + g * 4}" y="98" width="120" height="16" rx="3" fill="#F2B33D"/><rect x="${70 + g * 4}" y="80" width="110" height="18" rx="3" fill="#9BE15D"/><rect x="${56 + g * 4}" y="114" width="130" height="18" rx="3" fill="#FFF2C4"/><path d="M240 60l30-14 30 14-30 14z" fill="#FFF"/><path d="M252 66v14q18 10 36 0V66" fill="#C5E8E6"/>`],
  'Climate finance': ['#0F4C5C', '#1F7A8C', g => [0, 1, 2, 3, 4].map(i => `<rect x="${50 + i * 44}" y="${130 - (i + 1) * 16 - g * 2}" width="28" height="${(i + 1) * 16 + g * 2 + 30}" rx="5" fill="${i === 4 ? '#9BE15D' : '#7FD1E3'}" opacity="${.55 + i * .1}"/>`).join('') + `<path d="M50 104l44-20 44 6 44-26 44-22" stroke="#FFE08A" stroke-width="4" fill="none" stroke-linecap="round"/>`],
  'Adaptation': ['#6B4E2E', '#A67C52', g => [0, 1, 2, 3].map(i => `<path d="M0 ${80 + i * 22}h${200 - i * 30 + g * 6}q20 0 30 22H0z" fill="${i % 2 ? '#9BE15D' : '#D9C08A'}" opacity="${1 - i * .1}"/>`).join('') + `<circle cx="262" cy="46" r="16" fill="#FFE08A"/>`] };
const VISIT_SCENE = { visa: 'Education', flights: 'Water', stay: 'Cities', rides: 'Cities', transit: 'Cities', explore: 'Adaptation', buna: 'Agriculture', food: 'Agriculture', money: 'Climate finance', health: 'Health', emergency: 'Health', arrival: 'Youth' };
let coverN = 0;
function cover(theme, seed = 0, label = '', who = null, x = 235, sc = 1, photo = null) { if (photo && !S.save) return `<img class="cover photo" src="img/${photo}.webp" alt="${esc(label || theme)} (photo)" loading="lazy" decoding="async" width="800" height="500">`;
  const sc0 = SCENE[theme] || SCENE['Adaptation'], id = 'cg' + (coverN++), PE = window.PEOPLE, pp = who && PE && PE.P[who];
  return `<svg class="cover" viewBox="0 0 320 160" preserveAspectRatio="xMidYMid slice" role="img" aria-label="${esc(label || theme)} illustration${pp ? ' with an invented persona' : ''}"><defs><linearGradient id="${id}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${sc0[0]}"/><stop offset="1" stop-color="${sc0[1]}"/></linearGradient><radialGradient id="${id}h"><stop offset="0" stop-color="#fff" stop-opacity=".38"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient></defs><rect width="320" height="160" fill="url(#${id})"/>${sc0[2](seed % 5)}${pp ? `<circle cx="${x}" cy="${160 - 70 * sc}" r="${74 * sc}" fill="url(#${id}h)"/>${PE.person(pp, x, 160, sc)}` : ''}</svg>`; }
// ---- real photos (openly licensed, Wikimedia Commons via Openverse; credits at #/menu/credits). Data saver falls back to illustrations.
const THEME_PHOTOS = { 'Climate finance': ['plenary2_4', 'plenary2_1', 'conference_5'], 'Adaptation': ['terraces_0', 'cracked_4', 'river_1'], 'Energy': ['solar_4', 'solar_2', 'geothermal_4', 'wind_1'], 'Water': ['water_4', 'river_0', 'river_1'], 'Agriculture': ['teff_2', 'forest_3', 'market_4'], 'Youth': ['youth_2', 'youth_3', 'conference_0'], 'Health': ['stetho_3', 'health_5', 'stetho_1'], 'Education': ['classroom_5', 'workshop_0', 'workshop_1'], 'Forests': ['entoto_3', 'treeplanting_3', 'entoto_0'], 'Cities': ['lightrail_0', 'addis_1', 'city_1', 'lightrail_4'] };
const themePhoto = (th, n) => { const l = THEME_PHOTOS[th] || THEME_PHOTOS['Adaptation']; return l[n % l.length]; };
const sPhoto = s => themePhoto(s.theme, Math.floor(parseInt(s.id.slice(1), 10) / 10));
const VISIT_PHOTO = { visa: 'passport_2', flights: 'airport_0', stay: 'hotel_3', rides: 'taxi_0', transit: 'lightrail_4', explore: 'entoto_0', buna: 'coffee_3', food: 'injera_4', money: 'market_4', health: 'stetho_1', emergency: 'health_5', arrival: 'airport_5' };
const NEWS_PHOTO = ['airport_5', 'river_0', 'cracked_4', 'plenary2_4', 'cookstove2_0', 'plenary2_1', 'youth_3', 'entoto_3', 'terraces_0'];
const nPhoto = n => NEWS_PHOTO[parseInt(n.id.slice(1), 10) % 9];
// D44 cross-links: Visit guides <-> Map categories
const GUIDE_MAP = { health: ['hospital', 'Find hospitals and clinics on the map'], emergency: ['hospital', 'Nearest hospitals on the map'], transit: ['transport', 'Stations and stops on the map'], rides: ['transport', 'Pick-up points on the map'], stay: ['hotel', 'Hotels on the map'], explore: ['attraction', 'Sights on the map'], buna: ['cafe', 'Cafés on the map'], money: ['atm', 'ATMs on the map'] };
const MAP_GUIDE = { hospital: ['emergency', 'Emergency & help guide'], transport: ['transit', 'Airport & public transport guide'], hotel: ['stay', 'Where to stay guide'], cafe: ['buna', 'Coffee culture guide'], atm: ['money', 'Money, SIM & internet guide'], attraction: ['explore', 'Explore Addis guide'] };
const VISIT_WHO = { visa: 'officer', flights: 'traveller', stay: 'traveller', rides: 'driver', transit: 'traveller', explore: 'guide', buna: 'buna', food: 'chef', money: 'banker', health: 'nurse', emergency: 'volunteer', arrival: 'volunteer' };
const NEWS_WHO = ['delegate', 'reporter', 'student', 'banker', 'journalist', 'P12', 'volunteer', 'P11', 'P08'];
const lead = s => (s.speakers && s.speakers[0]) || 'delegate';
const nThemeOf = n => ['Climate finance', 'Adaptation', 'Education', 'Energy', 'Forests', 'Youth', 'Forests', 'Health', 'Adaptation'][parseInt(n.id.slice(1), 10) % 9];
// ---- card components
const sessCard = (s, wide) => { const sv = S.saved.has(s.id);
  return `<article class="scard ${wide ? 'wide' : ''}"><a class="scard-link" href="#/session/${s.id}" aria-label="${esc(sTitle(s))}, ${dayLabel(s.day)} ${s.start}"></a>
  <div class="scard-art">${cover(s.theme, parseInt(s.id.slice(1), 10), s.theme, lead(s), 240, 1.12, sPhoto(s))}<span class="badge-time">${svg('clock')}${dayLabel(s.day)} · ${s.start}</span>${s.open_to_public ? `<span class="badge-pub">${t('Open to public')}</span>` : ''}</div>
  <div class="scard-body"><span class="kick">${esc(s.format)} · ${esc(s.theme)}</span><b lang="${S.lang}">${esc(sTitle(s))}</b><span class="where">${svg('map-pin')}${esc(s.room)}</span></div>
  <button class="fab-star" data-save="${s.id}" aria-pressed="${sv}" aria-label="${sv ? 'Remove from' : 'Save to'} My agenda">${svg('star')}</button></article>`; };
const newsCard = (n, i) => `<a class="ncard" href="#/updates/news">${cover(nThemeOf(n), i, n.type, NEWS_WHO[parseInt(n.id.slice(1), 10) % 9], 205, .95, nPhoto(n))}<div class="ncard-body"><span class="kick">${esc(n.type)} · ${esc(n.src)}</span><b>${esc(n.title)}</b><small>${dayLabel(n.day)}</small></div></a>`;
const shelf = (title, link, items) => `<h2 class="sh">${title}${link ? ` <a href="${link[1]}">${link[0]}</a>` : ''}</h2><div class="shelf" tabindex="0" role="region" aria-label="${String(title).replace(/<[^>]+>/g, '')}">${items}</div>`;
const ACT = [['#/menu/learn/cop', 'ticket', 'Can I attend?', 'a1'], ['#/programme/schedule?public=1', 'users', 'Open to public', 'a2'], ['#/visit/emergency', 'siren', 'Emergency & help', 'a3'], ['#/map?acc=1', 'map-pin', 'Venue map', 'a4']];
// ---- PWA: install, real offline state, update notice
const PWA = { prompt: null, standalone: (() => { try { return matchMedia('(display-mode: standalone)').matches || navigator.standalone === true; } catch { return false; } })(), ios: /iphone|ipad|ipod/i.test(navigator.userAgent), update: null };
window.addEventListener('beforeinstallprompt', e => { e.preventDefault(); PWA.prompt = e; if (/^(home|menu)/.test(route())) render(); });
window.addEventListener('appinstalled', () => { PWA.prompt = null; PWA.standalone = true; toast('Installed — open COP32 from your home screen'); render(); });
window.addEventListener('online', () => { S.offline = false; toast('Back online'); render(); });
window.addEventListener('offline', () => { S.offline = true; toast('You are offline — saved content still works'); render(); });
if ('serviceWorker' in navigator && (location.protocol === 'https:' || location.hostname === 'localhost')) {
  try { navigator.serviceWorker.register('sw.js', { updateViaCache: 'none' }).then(reg => { reg.addEventListener('updatefound', () => { const w = reg.installing; if (!w) return; w.addEventListener('statechange', () => { if (w.state === 'installed' && navigator.serviceWorker.controller) { PWA.update = w; render(); } }); }); }).catch(() => {});
    const hadController = !!navigator.serviceWorker.controller; navigator.serviceWorker.addEventListener('controllerchange', () => { if (hadController && !PWA.reloaded) { PWA.reloaded = true; location.reload(); } }); } catch {} }
const canInstall = () => !PWA.standalone && (PWA.prompt || PWA.ios);
const installCard = () => canInstall() ? `<div class="install"><span class="install-ic"><img src="icons/icon-192.png" alt="" width="48" height="48"></span><div class="rt"><b>Install the app</b><small>${PWA.prompt ? 'Add COP32 to your home screen. Works offline.' : 'Tap Share, then “Add to Home Screen”.'}</small></div>${PWA.prompt ? `<button class="btn go" id="install">Install</button>` : ''}</div>` : '';
// ---- screens
const V = {};
V.home = () => {
  const crit = D.alerts.find(a => a.severity === 'critical'), saved = D.sessions.filter(s => S.saved.has(s.id)).sort((a, b) => (a.day + a.start).localeCompare(b.day + b.start));
  const next = saved.length ? saved : D.sessions.filter(s => s.open_to_public).slice(0, 4);
  const hero = { pre: [`Before the conference · sample`, `Plan your trip to Addis Ababa`, `<div class="count"><span><b>24</b><small>days</small></span><span><b>06</b><small>hours</small></span><span><b>50</b><small>sessions</small></span></div>`, ['#/visit', 'luggage', 'Start planning']],
    during: [t('Welcome to Addis Ababa'), t('Plan your days at the conference'), `<p lang="am">እንኳን ደህና መጡ። ጉዞዎን ያቅዱ።</p>`, ['#/programme/schedule', 'calendar', t('Browse programme')]],
    post: [`After the conference · sample`, `Outcomes and recordings`, `<p>Catch up on decisions, sessions and reports.</p>`, ['#/updates/live', 'play', 'Live &amp; recorded']] }[S.phase];
  return `<section class="hello"><div><div class="eyebrow">${dayLabel(DAYS[0])} · Sample</div><h1 class="title">${t('Today')}</h1></div><a class="searchpill" href="#/search" aria-label="${tp('Search')}">${svg('search')}</a></section>
  ${S.offline ? `<div class="status offline">${svg('wifi-off')}Offline — showing saved content (updated 09:12 EAT)</div>` : ''}
  <article class="hero">${S.save ? '' : `<img class="hero-photo" src="img/addis_1.webp" alt="" loading="eager" decoding="async">`}<div class="hero-in"><div class="kicker">${hero[0]}</div><h2>${hero[1]}</h2>${hero[2]}<a class="btn go" href="${hero[3][0]}">${svg(hero[3][1])}${hero[3][2]}</a></div>${hills}</article>
  ${crit ? `<div role="alert"><a class="alert-card" href="#/updates/alerts"><span class="ac-ic">${svg('triangle-alert')}</span><span><b>${esc(S.lang === 'am' ? crit.msg_am : crit.msg_en)}</b><small>Live alert · 10:05 · tap for all alerts</small></span>${chev()}</a></div>` : ''}
  ${installCard()}<div class="actions-grid">${ACT.map(([h, ic, l, c]) => `<a class="act ${c}" href="${h}"><span class="act-ic">${svg(ic)}</span><b>${t(l)}</b></a>`).join('')}</div>
  ${shelf(saved.length ? t('Up next') : 'Open to everyone', ['My agenda', '#/programme/agenda'], next.slice(0, 6).map(s => sessCard(s)).join(''))}
  ${shelf('Explore Addis', ['All guides', '#/visit'], D.visit.filter(v => ['buna', 'explore', 'food', 'transit'].includes(v.id)).map((v, i) => `<a class="vcard" href="#/visit/${v.id}">${cover(VISIT_SCENE[v.id], i + 2, v.en, VISIT_WHO[v.id], 175, .95, VISIT_PHOTO[v.id])}<span class="vcard-ic">${svg(v.icon)}</span><b>${esc(v.en)}</b></a>`).join(''))}
  ${shelf('Featured voices', ['See all', '#/programme/speakers'], D.speakers.slice(0, 8).map(p => `<a class="pcard" href="#/programme/speakers">${avatar(p.id, true)}<b>${esc(p.name)}</b><small>${esc(p.role)}</small></a>`).join(''))}
  <h2 class="sh">Highlights <a href="#/updates/news">All news</a></h2><div class="ngrid">${D.news.slice(0, 3).map(newsCard).join('')}</div>
  <p class="fine">All people and content are invented sample data. Photos: openly licensed, <a href="#/menu/credits">see credits</a>.</p>`; };
V.programme = (p, q) => { const k = p[1] || 'schedule';
  let body = '';
  if (k === 'schedule' || k === 'side') {
    const day = q.get('day') || DAYS[0], pub = q.get('public') === '1';
    const list = D.sessions.filter(s => (k === 'side' ? s.format === 'Side event' : s.day === day) && (!pub || s.open_to_public)).sort((a, b) => (a.day + a.start).localeCompare(b.day + b.start));
    body = `${k === 'schedule' ? `<nav class="days" aria-label="Day">${DAYS.map(d => { const [w, n] = dayLabel(d).split(' '); return `<a href="#/programme/schedule?day=${d}${pub ? '&public=1' : ''}" ${d === day ? 'aria-current="true"' : ''}><small>${w}</small><b>${n}</b></a>`; }).join('')}</nav>` : ''}
      <div class="caps"><a class="cap" aria-current="${pub}" href="#/programme/${k}?${k === 'schedule' ? 'day=' + day + '&' : ''}${pub ? '' : 'public=1'}">${pub ? svg('check') : svg('users')}${t('Open to public')}</a><a class="cap" href="#/programme/agenda">${svg('star')}${t('Saved')} · ${S.saved.size}</a></div>
      ${list.length ? `<div class="sgrid">${list.map(s => sessCard(s, true)).join('')}</div>` : emptyState('No sessions match', 'Try another day or clear the filter.', 'calendar')}
      <p class="fine">Times in East Africa Time (EAT). Sample data.</p>`;
  } else if (k === 'speakers') body = `<div class="pgrid">${D.speakers.map(s => `<a class="pcard big" href="#/programme/speakers">${avatar(s.id, true)}<b>${esc(s.name)}</b><small>${esc(s.role)}</small><span class="org">${esc(s.org)}</span></a>`).join('')}</div>`;
  else if (k === 'exhibitors') body = `<div class="ngrid two">${D.exhibitors.map((e, i) => `<a class="vcard tall" href="#/programme/exhibitors">${cover(e.theme, i, e.theme, ['P13', 'P10', 'P03', 'P11', 'P07', 'P17', 'P06', 'P05'][i % 8], 165, .95, ['exhibition_3', 'exhibition_2', 'exhibition_4', 'exhibition_5'][i % 4])}<span class="vcard-ic">${svg(['layers', 'landmark', 'mountain', 'building-2'][i % 4])}</span><b>${esc(e.name)}</b><small>${e.zone} · ${e.theme}</small></a>`).join('')}</div>`;
  else if (k === 'agenda') { const l = D.sessions.filter(s => S.saved.has(s.id)).sort((a, b) => (a.day + a.start).localeCompare(b.day + b.start));
    const changes = D.alerts.filter(a => a.severity !== 'critical' && /room|moves|change|delayed/i.test(a.msg_en)).slice(0, 2).map((a, i) => notice(a.severity === 'warning' ? 'warning' : 'info', esc(S.lang === 'am' ? a.msg_am : a.msg_en), `<a href="#/updates/alerts">All alerts</a>`, `10:0${i}`)).join('');
    body = (l.length ? changes : '') + (l.length ? `${DAYS.filter(d => l.some(s => s.day === d)).map(d => `<h2 class="sh">${dayLabel(d)}</h2><div class="sgrid">${l.filter(s => s.day === d).map(s => sessCard(s, true)).join('')}</div>`).join('')}<button class="btn tinted wide" style="margin-top:var(--s-5)" data-toast="Calendar export is a sample in this prototype">${svg('calendar-plus')}Add all to calendar</button>`
      : emptyState('No saved sessions yet', 'Tap the star on any session card to build your agenda.', 'star', `<a class="btn go" href="#/programme/schedule">${svg('calendar')}Browse schedule</a>`)); }
  return `${largeTitle(t('Programme'), 'Sample programme', `<a class="searchpill" href="#/search" aria-label="${tp('Search')}">${svg('search')}</a>`)}${segc([['schedule', 'Schedule'], ['side', 'Side events'], ['speakers', 'Speakers'], ['exhibitors', 'Exhibitors'], ['agenda', 'My agenda']], k, 'programme')}${body}`; };
V.session = p => { const s = D.sessions.find(x => x.id === p[1]); if (!s) return notFound(); const sv = S.saved.has(s.id);
  const spk = (s.speakers || []).map(id => D.speakers.find(x => x.id === id)).filter(Boolean);
  return `<div class="detail-art">${cover(s.theme, parseInt(s.id.slice(1), 10), s.theme, lead(s), 240, 1, sPhoto(s))}</div>
  <div class="detail-sheet"><span class="kick">${esc(s.format || 'Session')} · ${esc(s.theme)}</span><h2 class="dt" lang="${S.lang}">${esc(sTitle(s))}</h2>
  <div class="meta">${s.open_to_public ? `<span class="pill ok">${svg('check')}${t('Open to public')}</span>` : `<span class="pill warn">${svg('ticket')}Badge required (sample)</span>`}<span class="pill tint">${esc(s.theme)}</span></div>
  <div class="facts"><div class="fact">${svg('calendar')}<b>${dayLabel(s.day)}</b><small>${s.start}–${s.end} EAT</small></div><div class="fact">${svg('clock')}<b>${mins(s)} min</b><small>Duration</small></div><a class="fact" href="#/map">${svg('map-pin')}<b>${esc(s.room)}</b><small>Show on map</small></a></div>
  <div class="actions"><button class="btn ${sv ? 'tinted' : 'go'} grow" data-save="${s.id}" aria-pressed="${sv}">${svg('star')}${sv ? t('Saved') : 'Save to My agenda'}</button><button class="btn plain round" data-toast="Sharing is a sample in this prototype" aria-label="Share">${svg('share')}</button></div>
  <h2 class="sh">About</h2><p class="prose" lang="${S.lang}">${esc(S.lang === 'am' ? s.body_am : s.body_en)}</p>
  ${(() => { const TERMS = { 'Climate finance': ['Climate finance', 'NDC'], 'Adaptation': ['Adaptation', 'Loss and damage'], 'Energy': ['Emissions', 'Mitigation'], 'Water': ['Adaptation'], 'Agriculture': ['Adaptation', 'Emissions'], 'Youth': ['COP'], 'Health': ['Adaptation'], 'Education': ['COP', 'Mitigation'], 'Forests': ['Carbon sink', 'Emissions'], 'Cities': ['Mitigation', 'Emissions'] }; const terms = (TERMS[s.theme] || []).map(x => D.glossary.find(g => g[0] === x)).filter(Boolean); return terms.length ? `<h2 class="sh">Terms in this session</h2><div class="group">${terms.map(([a, b]) => `<a class="row notile" href="#/menu/learn/glossary"><span class="rt"><b>${esc(a)}</b><small>${esc(b)} (sample)</small></span>${chev()}</a>`).join('')}</div>` : ''; })()}
  ${spk.length ? `<h2 class="sh">${t('Speakers')}</h2><div class="pgrid">${spk.map(x => `<a class="pcard big" href="#/programme/speakers">${avatar(x.id, true)}<b>${esc(x.name)}</b><small>${esc(x.role)}</small><span class="org">${esc(x.org)}</span></a>`).join('')}</div>` : ''}
  <p class="src">${timeStr(s)} · Source: sample dataset · last updated 10:05 EAT</p></div>`; };
V.map = (p, q) => { const cats = [['all', 'All', 'layers'], ['transport', 'Transport', 'train-front'], ['attraction', 'Sights', 'landmark'], ['hotel', 'Hotels', 'bed'], ['cafe', 'Cafés', 'coffee'], ['hospital', 'Health', 'hospital'], ['atm', 'ATMs', 'banknote'], ['embassy', 'Embassies', 'building-2']], c = q.get('c') || 'all', a = q.get('acc') === '1';
  const pois = D.pois.filter(x => (c === 'all' || x.cat === c) && (!a || x.stepfree)), la = D.pois.map(x => x.lat), lo = D.pois.map(x => x.lon), [a0, a1, o0, o1] = [Math.min(...la), Math.max(...la), Math.min(...lo), Math.max(...lo)];
  const X = x => 30 + (x.lon - o0) / (o1 - o0) * 340, Y = x => 270 - (x.lat - a0) / (a1 - a0) * 240, sel = D.pois.find(x => x.id === q.get('poi'));
  const qs = (o) => { const u = new URLSearchParams({ c, ...(a ? { acc: '1' } : {}), ...o }); [...u.keys()].forEach(k => { if (u.get(k) === '') u.delete(k); }); return '#/map?' + u.toString(); };
  const ic = k => (cats.find(x => x[0] === k) || [0, 0, 'map-pin'])[2];
  return `${largeTitle(t('Map'), 'Addis Ababa · schematic')}
  <div class="caps"><a class="cap" aria-current="${a}" href="${qs({ acc: a ? '' : '1' })}">${svg('accessibility')}Step-free</a>${cats.map(([k, l, i]) => `<a class="cap" aria-current="${c === k}" href="${qs({ c: k })}">${svg(i)}${l}</a>`).join('')}</div>
  ${a ? notice('success', 'Step-free entrance: Gate B (sample)', 'Ramp and level path to all halls; accessible toilets in Hall A. Not real venue information.') : ''}
  <div class="mapbox"><span class="badge">Schematic placeholder · not a real map</span><svg viewBox="0 0 400 300" role="group" aria-label="Schematic map with ${pois.length} sample points">
  <rect width="400" height="300" fill="var(--c-surfaceAlt)"/><path d="M0 210 C90 180 160 240 260 200 S360 170 400 190 V300 H0Z" fill="var(--c-primarySoft)" opacity=".7"/>
  <path d="M0 150 C120 120 250 190 400 140" stroke="var(--c-surface)" stroke-width="12" fill="none"/><path d="M200 0 C190 100 230 200 210 300" stroke="var(--c-surface)" stroke-width="10" fill="none"/><path d="M40 0 C80 90 60 200 120 300" stroke="var(--c-surface)" stroke-width="6" fill="none"/>
  ${pois.map(x => { const on = sel && sel.id === x.id; return `<a href="${qs({ poi: x.id })}" aria-label="${esc(x.name)}"><circle cx="${X(x)}" cy="${Y(x)}" r="${on ? 13 : 9}" fill="${on ? 'var(--c-accent)' : 'var(--c-primary)'}" stroke="var(--c-surface)" stroke-width="3"/></a>`; }).join('')}</svg></div>
  ${sel ? `<article class="poi-sheet"><span class="act-ic big">${svg(ic(sel.cat))}</span><div class="rt"><b>${esc(sel.name)}</b><small>${esc(sel.desc)}${sel.stepfree ? ' · Step-free (sample)' : ''}</small></div><a class="btn go" href="#" data-linkout="your device's map app">${svg('external-link')}Directions</a></article>${MAP_GUIDE[sel.cat] ? (([v, l]) => `<a class="feature slim" href="#/visit/${v}"><span class="act-ic big">${svg('luggage')}</span><div class="feature-body"><b>${l}</b><small>Offline guide in Visit</small></div>${chev()}</a>`)(MAP_GUIDE[sel.cat]) : ''}`
    : shelf('Nearby places', null, D.pois.slice(0, 8).map((x, i) => `<a class="placecard" href="${qs({ poi: x.id })}"><span class="act-ic">${svg(ic(x.cat))}</span><b>${esc(x.name)}</b><small>${x.cat}</small></a>`).join(''))}`; };
V.visit = p => { const g = D.visit.find(x => x.id === p[1]);
  if (g) return `<div class="detail-art">${cover(VISIT_SCENE[g.id], 3, g.en, VISIT_WHO[g.id], 240, 1, VISIT_PHOTO[g.id])}<span class="detail-ic">${svg(g.icon)}</span></div><div class="detail-sheet"><span class="kick">Visit guide · sample</span><h2 class="dt">${g.am && S.lang === 'am' ? `<span lang="am">${esc(g.am)}</span>` : esc(g.en)}</h2>
    <div class="meta">${g.link ? `<span class="pill info">${svg('external-link')}Links to an outside site</span>` : `<span class="pill ok">${svg('circle-check')}Works offline</span>`}</div>
    <p class="prose">${esc(g.body)}</p>${g.link ? `<a class="btn go wide" href="#" data-linkout="the ${esc(g.en.toLowerCase())} provider (sample)">${svg('external-link')}Open official or partner site</a>` : ''}
    ${GUIDE_MAP[g.id] ? (([c, l]) => `<a class="feature slim" href="#/map?c=${c}"><span class="act-ic big">${svg('map-pin')}</span><div class="feature-body"><b>${l}</b><small>Opens the venue and city map</small></div>${chev()}</a>`)(GUIDE_MAP[g.id]) : ''}
    <p class="src">Source: Editorial (sample) · last verified: never (placeholder)</p></div>`;
  return `${largeTitle(t('Visit'), 'Your trip to Addis Ababa')}
  <a class="feature" href="#/visit/buna">${cover('Agriculture', 1, 'Coffee ceremony', 'buna', 268, 1.05, 'coffee_3')}<div class="feature-body"><span class="kick">Don't miss</span><b>Coffee culture (Buna)</b><small>Where to see a traditional coffee ceremony</small></div></a>
  <div class="vgrid">${D.visit.map((x, i) => `<a class="vcard tall" href="#/visit/${x.id}">${cover(VISIT_SCENE[x.id], i, x.en, VISIT_WHO[x.id], 165, .95, VISIT_PHOTO[x.id])}<span class="vcard-ic">${svg(x.icon)}</span><b>${x.am && S.lang === 'am' ? `<span lang="am">${esc(x.am)}</span>` : esc(x.en)}</b><small>${x.link ? 'Link-out' : 'Offline guide'}</small></a>`).join('')}</div>`; };
V.updates = p => { const k = p[1] || 'news'; let b = '';
  if (k === 'news') b = `<a class="feature" href="#/updates/news">${cover(nThemeOf(D.news[0]), 0, D.news[0].type, 'delegate', 268, 1.05, nPhoto(D.news[0]))}<div class="feature-body"><span class="kick">${esc(D.news[0].type)} · ${esc(D.news[0].src)}</span><b>${esc(D.news[0].title)}</b><small>${dayLabel(D.news[0].day)}</small></div></a><div class="ngrid two">${D.news.slice(1).map((n, i) => newsCard(n, i + 1)).join('')}</div>`;
  else if (k === 'alerts') b = `<a class="alert-card" href="#/visit/emergency" style="margin:0 0 var(--s-4)"><span class="ac-ic">${svg('siren')}</span><span><b>${t('Emergency & help')}</b><small>Numbers, nearest hospitals, first aid</small></span>${chev()}</a>` + D.alerts.map((a, i) => notice(a.severity === 'critical' ? 'critical' : a.severity === 'warning' ? 'warning' : 'info', esc(S.lang === 'am' ? a.msg_am : a.msg_en), 'Sample feed', `10:0${i}`)).join('');
  else if (k === 'press') b = `<div class="ngrid two">${D.news.filter(n => n.type !== 'Explainer').map((n, i) => newsCard(n, i)).join('')}</div><a class="feature slim" href="#/menu/library"><span class="act-ic big">${svg('library')}</span><div class="feature-body"><b>Press kit (sample)</b><small>Fact sheets and background · no logos (independent platform)</small></div>${chev()}</a>`;
  else if (k === 'live') b = D.live.map((l, i) => `<article class="live ${l.status}">${cover(['Youth', 'Cities', 'Adaptation'][i], i, l.title, ['P16', 'P03', 'P18'][i], 255, 1.05, ['conference_2', 'youth_2', 'conference_0'][i])}<div class="live-over">${l.status === 'live' ? `<span class="pill bad"><span class="live-dot"></span>LIVE</span>` : l.status === 'scheduled' ? `<span class="pill">Starts 14:00 EAT</span>` : `<span class="pill">Recording · 1 h 12 min</span>`}<b>${esc(l.title)}</b></div><button class="play" data-toast="Sample only: no real stream" aria-label="Play ${esc(l.title)}">${svg('play')}</button></article>`).join('') + `<a class="feature slim" href="#/menu/archive"><span class="act-ic big">${svg('archive')}</span><div class="feature-body"><b>Past events archive</b><small>Recordings from earlier editions (sample)</small></div>${chev()}</a>`;
  else if (k === 'explainers') b = `<div class="ngrid two">${D.news.filter(n => n.type === 'Explainer').map((n, i) => `<a class="ncard" href="#/updates/explainers">${cover(['Education', 'Climate finance', 'Adaptation'][i], i, 'Explainer', ['P12', 'P05', 'P01'][i], 205, .95, ['cracked_4', 'plenary2_1', 'terraces_0'][i])}<div class="ncard-body"><span class="kick">Explainer · 3 min</span><b>${esc(n.title)}</b></div></a>`).join('')}<a class="ncard" href="#/menu/learn/glossary">${cover('Youth', 2, 'Glossary', 'student', 205, .95, 'classroom_5')}<div class="ncard-body"><span class="kick">A–Z</span><b>Glossary of COP words</b></div></a></div>`;
  else b = `<a class="feature" href="#/updates/digest">${cover('Water', 4, 'Daily digest', 'reporter', 268, 1.05, 'addis_0')}<div class="feature-body"><span class="kick">Every evening · 19:00 EAT</span><b>Daily digest (sample)</b><small>A short summary of the day</small></div></a>`;
  return `${largeTitle(t('Updates'), 'News, alerts and media', `<a class="searchpill" href="#/search" aria-label="${tp('Search')}">${svg('search')}</a>`)}${segc([['news', 'News'], ['alerts', 'Alerts'], ['press', 'Press'], ['live', 'Live & recorded'], ['explainers', 'Explainers'], ['digest', 'Digest']], k, 'updates')}${b}`; };
// ---- profile & settings sheet (#/menu): replaces the v1 ☰ menu; same destinations (D53)
V.menu = p => { const k = p[1];
  if (!k) return `${largeTitle(t('Settings'), 'Profile & settings')}
    ${S.signed ? `<div class="prof"><span class="pav">SA</span><div class="rt"><b>Selam Anbessa</b><small>selam@example.org · sample account</small></div></div>`
      : `<div class="prof"><span class="pav">${svg('user-round')}</span><div class="rt"><b>Guest</b><small>Using the app without an account</small></div></div><button class="btn wide" id="signin" style="margin-top:var(--s-3)">${svg('log-in')}Sign in to sync your agenda</button><p class="gnote">Optional. Everything works without an account; your saved sessions stay on this phone (D21).</p>`}
    ${canInstall() ? `<div style="margin-top:var(--s-4)">${installCard()}</div>` : PWA.standalone ? `<p class="gnote">${svg('circle-check')} Installed as an app</p>` : ''}
    <div class="glabel">Account</div><div class="group">${row({ href: '#/programme/agenda', icon: 'bookmark', title: t('My agenda'), val: `${S.saved.size} saved` })}${row({ href: '#/updates/alerts', icon: 'bell-ring', tone: 'c2', title: 'Notifications', val: 'On' })}</div>
    <div class="glabel">Preferences</div><div class="group">${row({ href: '#/menu/settings', icon: 'languages', title: t('Language'), val: S.lang === 'am' ? '<span lang="am">አማርኛ</span>' : 'English' })}<div class="row"><span class="ri c4">${svg('sun-moon')}</span><label class="rt" for="s-dark"><b>Dark mode</b><small>${S.theme === 'auto' ? 'Matching your phone' : S.theme === 'dark' ? 'On' : 'Off (light)'}</small></label><input type="checkbox" role="switch" class="switch" id="s-dark" ${S.theme === 'dark' ? 'checked' : ''}></div>${row({ href: '#/menu/settings', icon: 'type', tone: 'c5', title: 'Text size', val: S.scale > 1 ? '200%' : 'Default' })}${row({ href: '#/menu/settings', icon: 'clock', tone: 'c2', title: 'Time zone', val: 'EAT' })}</div>
    <div class="glabel">Learn &amp; library</div><div class="group">${row({ href: '#/menu/learn', icon: 'book-open', title: 'Learn', sub: 'COP explained, climate basics, glossary' })}${row({ href: '#/menu/library', icon: 'library', tone: 'c5', title: 'Library', sub: 'Documents and reports' })}${row({ href: '#/menu/archive', icon: 'archive', tone: 'c4', title: 'Archive', sub: 'Past editions' })}</div>
    <div class="glabel">Privacy</div><div class="group">${row({ href: '#/menu/settings', icon: 'shield', title: 'Privacy & data' })}${row({ href: '#/menu/settings', icon: 'trash-2', tone: 'c3', title: '<span style="color:var(--c-danger)">Delete my data</span>' })}</div>
    <div class="glabel">Help</div><div class="group">${row({ href: '#/menu/help', icon: 'circle-help', title: 'Help & FAQ' })}${row({ href: '#/menu/about', icon: 'info', tone: 'c5', title: 'About this prototype', val: 'v0.6.1' })}${row({ href: '#/menu/credits', icon: 'library', tone: 'c4', title: 'Photo credits' })}</div>
    ${S.signed ? `<button class="btn danger wide" id="signout" style="margin-top:var(--s-7)">${svg('log-out')}Sign out</button>` : ''}
    <p class="fine">PROTOTYPE · sample data · not an official COP32 app</p>`;
  if (k === 'learn') { if (p[2] === 'glossary') return `${largeTitle('Glossary', 'Learn')}<div class="group">${D.glossary.map(([a, b]) => `<div class="row notile"><span class="rt"><b>${a}</b><small>${b} (sample wording)</small></span></div>`).join('')}</div>`;
    if (p[2] === 'cop') return `${largeTitle('Can I attend?', 'COP explained')}${notice('warning', 'Not announced yet', 'Public-access rules for COP32 have not been officially published. This page will update when they are.')}<p class="prose">Sample content — to be written and verified. Most COPs have a badge-only Blue Zone and a Green Zone open to the public; that may not apply here.</p><span class="pill warn">TBC</span>`;
    return `${largeTitle('Learn', 'Climate, explained simply')}<div class="ngrid two">${[['cop', 'COP explained & Can I attend?', 'Youth'], ['glossary', 'Glossary of COP words', 'Education'], ['basics', 'Climate basics', 'Water'], ['africa', 'Africa & Ethiopia climate story', 'Adaptation'], ['legacy', 'Green Legacy tree planting', 'Forests']].map(([i, l, th], n) => `<a class="ncard" href="#/menu/learn/${i}">${cover(th, n, l, ['P18', 'P12', 'student', 'P09', 'P11'][n], 205, .95, ['conference_0', 'classroom_5', 'wind_1', 'river_1', 'treeplanting_3'][n])}<div class="ncard-body"><span class="kick">${i === 'cop' || i === 'glossary' ? 'Learn' : 'Sample'}</span><b>${l}</b></div></a>`).join('')}</div>`; }
  if (k === 'library') return `${largeTitle('Library', 'Documents & reports')}<div class="group">${D.docs.map(d => row({ icon: 'file-text', title: esc(d.title), sub: `${d.kind} · ${d.size}`, val: '' })).join('')}</div>`;
  if (k === 'archive') return `${largeTitle('Archive', 'Past editions')}<div class="group">${D.archive.map(a => row({ icon: 'archive', tone: 'c4', title: esc(a.title) })).join('')}</div>`;
  if (k === 'help') return `${largeTitle('Help & FAQ')}<div class="group">${['How do I save a session?', 'Does the app work offline?', 'Is this the official COP32 app?', 'How do I change the language?'].map(x => row({ title: x })).join('')}</div><p class="fine">Sample FAQ entries.</p>`;
  if (k === 'about') return `${largeTitle('About')}${notice('warning', 'Independent platform — not an official COP32, UNFCCC or government product.', 'This is a prototype with invented sample data.')}<p class="prose muted">Amharic text in this prototype is machine-drafted and has not been reviewed by a native speaker. Design: Highland Mist v0.2. Icons: Lucide (ISC). Fonts: Atkinson Hyperlegible Next and Noto Sans Ethiopic (OFL).</p><div class="group">${row({ href: '#/test', icon: 'flask-conical', title: 'Tree-test dry run' })}${row({ href: '#/states', icon: 'layers', tone: 'c5', title: 'UI states gallery' })}</div>`;
  if (k === 'credits') { let C = {}; try { C = window.CREDITS || {}; } catch {}
    return `${largeTitle('Photo credits', 'About')}<p class="prose muted">Photos are openly licensed (CC BY, CC BY-SA, CC0 or public domain) from Wikimedia Commons, found through Openverse. They were cropped and resized for this prototype. They show real places and events in general; they do not show COP32, and no person in them is connected with this prototype or its invented speakers.</p><div class="group">${Object.entries(C).map(([k, c]) => `<a class="row" href="${esc(c.source)}" target="_blank" rel="noopener"><img class="credit-thumb" src="img/${k}.webp" alt="" loading="lazy"><span class="rt"><b>${esc(c.title)}</b><small>${esc(c.creator)} · ${String(c.license).toUpperCase()} ${esc(c.version || '')}</small></span>${svg('external-link', 'chev')}</a>`).join('')}</div>`; }
  if (k === 'settings') return settings(); return notFound(); };
function settings() { const sw = (id, label, on, sub = '') => `<div class="row notile"><label class="rt" for="${id}"><b>${label}</b>${sub ? `<small>${sub}</small>` : ''}</label><input type="checkbox" role="switch" class="switch" id="${id}" ${on ? 'checked' : ''}></div>`;
  const opt = (label, items) => `<div class="row notile"><span class="rt"><b>${label}</b></span><span class="opt">${items}</span></div>`;
  return `${largeTitle(t('Settings'), 'Preferences')}
  <div class="group">${opt(t('Language'), `<button data-lang="en" aria-pressed="${S.lang === 'en'}">English</button><button data-lang="am" aria-pressed="${S.lang === 'am'}" lang="am">አማርኛ</button>`)}
  ${opt('Text size', `<button data-scale="1" aria-pressed="${S.scale === 1}">100%</button><button data-scale="2" aria-pressed="${S.scale === 2}">200%</button>`)}
  ${opt('Appearance', ['light', 'dark', 'auto'].map(x => `<button data-set-theme="${x}" aria-pressed="${S.theme === x}">${{ auto: 'Match phone', light: 'Light', dark: 'Dark' }[x]}</button>`).join(''))}
  ${sw('s-reduce', 'Reduce motion', S.reduce)}${sw('s-save', 'Data saver', S.save, 'Low-data mode: shows light illustrations instead of photos')}</div>
  <div class="glabel">Demo controls</div><div class="group">${sw('s-off', 'Simulate offline', S.offline)}${opt('Event phase', ['pre', 'during', 'post'].map(x => `<button data-phase="${x}" aria-pressed="${S.phase === x}">${x}</button>`).join(''))}</div>
  <div class="glabel">Privacy &amp; data</div><div class="group"><div class="row notile"><span class="rt"><small>This prototype stores only your settings, saved sessions and test results in this browser. Nothing is sent anywhere.</small></span></div></div>
  <button class="btn danger wide" id="del" style="margin-top:var(--s-4)">${svg('trash-2')}Delete my data</button>`; }
V.search = (p, q) => { const raw = q.get('q') || '', f = fold(raw); let res = [];
  if (f) { const m = (...a) => a.some(x => fold(x).includes(f));
    res = [...D.sessions.filter(s => m(s.title_en, s.title_am, s.theme)).map(s => ['Sessions', sTitle(s), `session/${s.id}`, 'calendar']), ...D.speakers.filter(s => m(s.name, s.role)).map(s => ['People', s.name, 'programme/speakers', 'user-round']),
      ...D.pois.filter(x => m(x.name, x.cat)).map(x => ['Places', x.name, `map?poi=${x.id}`, 'map-pin']), ...D.visit.filter(v => m(v.en, v.am || '')).map(v => ['Visit', v.en, `visit/${v.id}`, 'luggage']), ...D.glossary.filter(g => m(g[0], g[1])).map(g => ['Glossary', g[0], 'menu/learn/glossary', 'languages']), ...D.news.filter(n => m(n.title)).map(n => ['News', n.title, 'updates/news', 'newspaper'])]; }
  const groups = [...new Set(res.map(r => r[0]))];
  return `${largeTitle(t('Search'))}<form id="sf" role="search"><label class="vh" for="q">${t('Search')}</label><input type="search" id="q" value="${esc(raw)}" placeholder="Sessions, places, people" autocomplete="off"></form>
  <p class="fine" style="text-align:start;margin:var(--s-3) var(--s-2) 0">Ge'ez-aware: try <span lang="am">ዐዲስ</span> — it finds <span lang="am">አዲስ</span> (spike S3).</p>
  ${f ? (res.length ? groups.map(g => `<h2 class="sh">${g}</h2><div class="group">${res.filter(r => r[0] === g).slice(0, 8).map(r => row({ href: '#/' + r[2], icon: r[3], title: esc(r[1]) })).join('')}</div>`).join('') : `<div style="margin-top:var(--s-5)">${emptyState('No results', 'Check the spelling or try another word.', 'search')}</div>`) : ''}`; };
V.states = () => `${largeTitle('UI states', 'Gallery')}${notice('critical', 'Critical alert', 'Assertive announcement (sample)', '10:05')}${notice('warning', 'Warning', 'Sample')}${notice('info', 'Info', 'Sample')}${notice('success', 'Success', 'Sample')}
  <h2 class="sh">Empty</h2>${emptyState('No saved sessions yet', 'Tap the star on any session.', 'star')}
  <h2 class="sh">Error</h2>${notice('critical', 'Couldn’t refresh', 'Showing saved content from 09:12 EAT.')}<button class="btn tinted" data-toast="Retrying (sample)">${svg('rotate-cw')}Retry</button>
  <h2 class="sh">Offline / stale</h2><div class="status offline">${svg('wifi-off')}Offline — showing saved content (updated 09:12 EAT)</div>
  <h2 class="sh">Not announced (TBC)</h2><div class="group"><div class="row notile"><span class="rt"><b>Dates and venue</b><small>Not officially announced yet</small></span><span class="pill warn">TBC</span></div></div><button class="btn plain" style="margin-top:var(--s-3)" data-toast="We'll notify you (sample)">${svg('bell')}Notify me when announced</button>
  <h2 class="sh">Loading</h2><div class="group" style="padding:var(--s-4)"><div class="skel" style="width:70%"></div><div class="skel"></div><div class="skel" style="width:50%"></div></div>
  <h2 class="sh">Link-out</h2><button class="btn plain" data-linkout="an example provider">${svg('external-link')}Open example</button>`;
// ---- tree test (dry run)
const TREE = { Home: ['Next session', 'Alerts', 'Now & next', 'Shortcuts', 'Highlights'], Programme: ['Schedule (by day)', 'Side events', 'Speakers', 'Exhibitors & pavilions', 'My agenda'], Map: ['Venue map', 'City map', 'Directions', 'Accessibility'],
  Visit: ['Before you travel (Visa, Flights, Insurance info)', 'Stay (Hotels)', 'Getting around (Airport, Light rail, Buses, Ride apps)', 'Explore Addis (Attractions, Day trips)', 'Coffee culture', 'Food', 'Money & SIM', 'Health & safety', 'Emergency'],
  Updates: ['News', 'Alerts history', 'Press centre', 'Live & recorded', 'Explainers', 'Daily digest'],
  'Profile & settings': ['Learn (COP explained, Climate basics, Africa & Ethiopia, Green Legacy, Glossary)', 'Library (Documents, Reports)', 'Archive', 'Me & Settings (Language, Time zone, Notifications, Privacy & data)', 'Help & FAQ', 'About'] };
const TREE_MAP = { 'Getting around (Airport, Light rail, Buses, Ride apps)': ['visit/transit', 'visit/rides'], 'Before you travel (Visa, Flights, Insurance info)': ['visit/visa'], 'Coffee culture': ['visit/buna'], 'Press centre': ['updates/press'], 'Live & recorded': ['updates/live'], 'Archive': ['menu/archive'], 'Explainers': ['updates/explainers'],
  'Learn (COP explained, Climate basics, Africa & Ethiopia, Green Legacy, Glossary)': ['menu/learn'], 'Me & Settings (Language, Time zone, Notifications, Privacy & data)': ['menu/settings'], Accessibility: ['map'], 'Schedule (by day)': ['programme'], 'Side events': ['programme'], 'My agenda': ['programme'], Alerts: ['home'], 'Alerts history': ['updates'], Shortcuts: ['home'] };
V.test = (p) => { const task = S.task && D.tasks.find(x => x[0] === S.task);
  const hist = S.results.length ? `<div class="tablewrap"><table><tr><th>Task</th><th>Mode</th><th>First click</th><th>Path</th><th>OK</th></tr>${S.results.map(r => `<tr><td>${r.task}</td><td>${r.mode}</td><td>${esc(r.first)}</td><td>${esc(r.path)}</td><td>${r.ok ? 'Y' : 'N'}</td></tr>`).join('')}</table></div><div class="actions" style="margin-top:var(--s-4)"><button class="btn tinted" id="csv">Download CSV</button><button class="btn plain" id="clr">Clear results</button></div>` : '<p class="muted">No results yet.</p>';
  if (p[1] === 'tree' && task) return `${largeTitle('Text tree', task[0])}<p class="prose">${esc(task[1])}</p><p class="small muted">Click where you would look first, then the item.</p><div class="group tree" style="padding:var(--s-4)">${Object.entries(TREE).map(([k, v]) => `<ul><li><button data-tt="${esc(k)}" data-top="1">${k}</button><ul>${v.map(i => `<li><button data-tt="${esc(i)}" data-parent="${k}">${esc(i)}</button></li>`).join('')}</ul></li></ul>`).join('')}</div>`;
  return `${largeTitle('Tree-test dry run', 'Rehearsal only')}${notice('warning', 'Dry run only.', 'Not the real tree test (needs 10–15 real participants, EN and AM). Results stay in this browser.')}
  <div class="group">${D.tasks.map(x => `<div class="row notile" style="flex-wrap:wrap"><span class="rt"><b>${x[0]}</b><small>${esc(x[1])}</small></span><span class="opt"><button data-task="${x[0]}" data-mode="tree">Text tree</button><button data-task="${x[0]}" data-mode="app" aria-pressed="true">In the app</button></span></div>`).join('')}</div><h2 class="sh">Results</h2>${hist}`; };
let toastT; function toast(msg) { let el = $('.toast'); if (!el) { el = document.createElement('div'); el.className = 'toast'; el.setAttribute('role', 'status'); document.body.appendChild(el); } el.textContent = msg; el.classList.add('show'); clearTimeout(toastT); toastT = setTimeout(() => el.classList.remove('show'), 1800); }
function dialogBox(html, onOk) { const d = document.createElement('dialog'); d.setAttribute('aria-labelledby', 'dt'); d.innerHTML = html; document.body.appendChild(d); d.addEventListener('click', ev => { const b = ev.target.closest('button'); if (b) { d.close(); if (b.value === 'c' && onOk) onOk(); } }); d.addEventListener('close', () => d.remove()); d.showModal(); }
const finish = (mode, path, first, ok) => { S.results.push({ task: S.task, mode, first, path, ok }); store.set('results', S.results); const nxt = S.task; S.task = null; store.set('task', null); S.visited = []; S.firstTab = null; toast(ok ? `Correct (${nxt}).` : `Not the expected location (${nxt}).`); location.hash = '#/test'; };
// ---- render
const ROOTS = ['home', 'programme', 'map', 'visit', 'updates'];
function render() {
  setPrefs(); const full = route(), [pathPart, qs] = full.split('?'), p = pathPart.split('/'), q = new URLSearchParams(qs || ''), key = p[0] === 'session' ? 'programme' : p[0];
  S.visited.push(pathPart); if (!S.firstTab && S.task) S.firstTab = pathPart;
  const view = V[p[0]] || (() => notFound()); const title = { home: 'Today', programme: 'Programme', map: 'Map', visit: 'Visit', updates: 'Updates', menu: 'Settings', search: 'Search', test: 'Test', states: 'States', session: 'Session' }[p[0]] || 'Not found';
  document.title = `${title} — COP32 companion (PROTOTYPE)`;
  const task = S.task && D.tasks.find(x => x[0] === S.task);
  const isRoot = ROOTS.includes(p[0]) && p.length === 1 || (['programme', 'updates'].includes(p[0]) && p.length === 2);
  const backHref = p[0] === 'session' ? '#/programme' : p[0] === 'visit' ? '#/visit' : p[0] === 'menu' && p.length > 1 ? (p[1] === 'learn' && p[2] ? '#/menu/learn' : '#/menu') : p[0] === 'menu' || p[0] === 'search' ? '#/home' : '#/home';
  const lead = isRoot ? `<a class="mark" href="#/home" aria-label="COP32 companion, home"><b>C32</b><span>Companion</span></a>` : `<a class="back" href="${backHref}" ${p[0] === 'session' || p[0] === 'search' ? 'data-back="1"' : ''}>${svg('chevron-left')}${t('Back')}</a>`;
  app.innerHTML = `<header class="nav"><div class="lead">${lead}</div><span class="inline-title" aria-hidden="true">${tp(title)}</span>
    <a class="cb" href="#/updates/alerts" aria-label="Alerts, 1 unread">${svg('bell')}<span class="dot" aria-hidden="true"></span></a>
    <button class="lang" id="lg" aria-label="${S.lang === 'en' ? 'Switch language to Amharic' : 'Switch language to English'}"><span lang="${S.lang === 'en' ? 'am' : 'en'}">${S.lang === 'en' ? 'አማ' : 'EN'}</span></button>
    <a class="cb" href="#/menu" aria-label="Profile and settings" ${p[0] === 'menu' && !p[1] ? 'aria-current="page"' : ''}>${svg('circle-user-round')}</a></header>
    ${task && p[0] !== 'test' ? `<div class="taskbar"><strong>${task[0]}</strong> ${esc(task[1])} <button class="btn" id="found">I found it</button> <a href="#/test">Cancel</a></div>` : ''}
    ${S.offline && p[0] !== 'home' ? `<div class="status offline" style="margin:0 var(--gutter) var(--s-3)">${svg('wifi-off')}Offline — showing saved content</div>` : ''}${PWA.update ? `<div class="update-bar" role="status">New version ready <button class="btn go" id="upd">Refresh</button></div>` : ''}<main id="main" tabindex="-1" class="enter">${view(p, q)}</main>
    <div class="watermark" role="note">PROTOTYPE · sample data · not an official COP32 product</div>
    <nav class="tabs" aria-label="Main">${TABS.map(([k, l, i]) => `<a href="#/${k}" ${key === k ? 'aria-current="page"' : ''}>${svg(i)}<span>${t(l === 'Home' ? 'Today' : l)}</span></a>`).join('')}</nav>`;
  $('#main').focus({ preventScroll: true }); window.scrollTo(0, 0); onScroll();
}
function onScroll() { app.classList.toggle('scrolled', window.scrollY > 24); }
window.addEventListener('scroll', onScroll, { passive: true });
// ---- events
document.addEventListener('click', e => {
  const el = e.target.closest('[data-save],[data-lang],[data-scale],[data-set-theme],[data-phase],[data-linkout],[data-task],[data-tt],[data-toast],[data-back],#lg,#del,#found,#csv,#clr,#signin,#signout,#install,#upd'); if (!el) return;
  if (el.dataset.back && history.length > 1 && document.referrer !== undefined) { e.preventDefault(); history.back(); return; }
  if (el.dataset.save) { e.preventDefault(); const id = el.dataset.save, on = !S.saved.has(id); on ? S.saved.add(id) : S.saved.delete(id); store.set('saved', [...S.saved]);
    if (el.classList.contains('fab-star')) { document.querySelectorAll(`.fab-star[data-save="${id}"]`).forEach(b => { b.setAttribute('aria-pressed', on); b.setAttribute('aria-label', (on ? 'Remove from' : 'Save to') + ' My agenda'); }); }
    else { const y = window.scrollY; render(); window.scrollTo(0, y); onScroll(); }
    toast(on ? 'Added to My agenda' : 'Removed from My agenda'); }
  else if (el.id === 'lg' || el.dataset.lang) { S.lang = el.dataset.lang || (S.lang === 'en' ? 'am' : 'en'); store.set('lang', S.lang); S.visited.push('header/language'); render(); }
  else if (el.dataset.scale) { S.scale = +el.dataset.scale; store.set('scale', S.scale); render(); }
  else if (el.dataset.setTheme) { S.theme = el.dataset.setTheme; store.set('appearance', S.theme); render(); }
  else if (el.dataset.phase) { S.phase = el.dataset.phase; store.set('phase', S.phase); render(); }
  else if (el.dataset.toast) { toast(el.dataset.toast); }
  else if (el.dataset.linkout) { e.preventDefault(); dialogBox(`<h2 id="dt">You’re leaving the app</h2><p class="muted">Opening ${esc(el.dataset.linkout)}. We don’t share your data. (Sample interstitial — no real link.)</p><div class="dlg-actions"><button class="btn plain" value="x">Cancel</button><button class="btn" value="c">Continue</button></div>`, () => toast('Sample only: no real link')); }
  else if (el.dataset.task) { S.task = el.dataset.task; store.set('task', S.task); S.visited = []; S.firstTab = null; if (el.dataset.mode === 'tree') { S.mode = 'tree'; location.hash = '#/test/tree'; } else { S.mode = 'app'; location.hash = '#/home'; } }
  else if (el.dataset.tt) { const task = D.tasks.find(x => x[0] === S.task); if (el.dataset.top) { S.firstTab = el.dataset.tt; el.style.fontWeight = 700; return; }
    const ok = (TREE_MAP[el.dataset.tt] || [el.dataset.tt.toLowerCase()]).some(r => task[2].some(c => r === c || c.startsWith(r + '/') || r.startsWith(c + '/') || (r === 'menu/settings' && c === 'header/language'))); finish('tree', `${el.dataset.parent} > ${el.dataset.tt}`, S.firstTab || el.dataset.parent, ok); }
  else if (el.id === 'found') { const task = D.tasks.find(x => x[0] === S.task), last = route().split('?')[0]; finish('app', S.visited.filter(v => v !== 'test').join(' > '), S.firstTab || '', task[2].some(c => last === c || last.startsWith(c) || (c === 'header/language' && S.visited.includes('header/language')) || (c.startsWith('visit/') && last === c) || (c === 'programme' && last.startsWith('programme')) || (c === 'home' && last === 'home') || (c === 'updates' && last.startsWith('updates')) || (c === 'map' && last.startsWith('map')) || (c === 'menu/settings' && last.startsWith('menu/settings')))); }
  else if (el.id === 'del') { dialogBox(`<h2 id="dt">Delete your data?</h2><p class="muted">This removes your settings, saved sessions and test results from this browser.</p><div class="dlg-actions"><button class="btn plain" value="x">Cancel</button><button class="btn" style="background:var(--c-danger);color:var(--c-onDanger)" value="c">Delete</button></div>`, () => { store.clear(); S.saved = new Set(); S.results = []; S.lang = 'en'; S.theme = 'light'; S.scale = 1; S.task = null; S.signed = false; render(); toast('Your data was deleted'); }); }
  else if (el.id === 'install') { const pr = PWA.prompt; if (pr) { pr.prompt(); pr.userChoice.then(c => { if (c.outcome === 'accepted') PWA.prompt = null; render(); }).catch(() => {}); } }
  else if (el.id === 'upd') { if (PWA.update) { PWA.reloadOnUpdate = true; PWA.update.postMessage('skipWaiting'); } }
  else if (el.id === 'signin') { S.signed = true; store.set('signed', true); render(); toast('Signed in (sample account)'); }
  else if (el.id === 'signout') { S.signed = false; store.set('signed', false); render(); toast('Signed out'); }
  else if (el.id === 'csv') { const csv = 'task,mode,first_click,path,success\n' + S.results.map(r => [r.task, r.mode, r.first, r.path, r.ok ? 'Y' : 'N'].map(x => `"${String(x).replace(/"/g, '""')}"`).join(',')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = 'tree-test-dry-run.csv'; a.click(); }
  else if (el.id === 'clr') { S.results = []; store.set('results', []); render(); } });
document.addEventListener('change', e => { const i = e.target.id; if (i === 's-reduce') { S.reduce = e.target.checked; store.set('reduce', S.reduce); } else if (i === 's-save') { S.save = e.target.checked; store.set('dataSaver', S.save); } else if (i === 's-dark') { S.theme = e.target.checked ? 'dark' : 'light'; store.set('appearance', S.theme); } else if (i === 's-off') { S.offline = e.target.checked; toast(S.offline ? 'Offline mode (simulated)' : 'Back online'); } else return; render(); });
document.addEventListener('submit', e => { if (e.target.id === 'sf') { e.preventDefault(); location.hash = '#/search?q=' + encodeURIComponent($('#q').value); } });
window.addEventListener('hashchange', render); render();
})();
